local lighting = require "lighting.lighting_state"

go.property("radii", vmath.vector4())
go.property("color", vmath.vector4())

function init(self)
	local p3 = go.get_world_position()
	local p4 = vmath.vector4(p3.x, p3.y, p3.z, 1.0)
	self.id = lighting.add_light(p4, self.radii, self.color)
end

function update(self, dt)
	local p3 = go.get_world_position()
	local p4 = lighting.get_light(self.id)
	p4.x, p4.y, p4.z = p3.x, p3.y, p3.z
end
